### ISSUE TITLE
Cleanup: Reorganize top level files to minimize clutter

### ISSUE THREAD

**Issue by timkpaine** [jpmorganchase/nbcelltests#104]
- [x] move azure pipelines to ci folder, reroute in azure
- [x] move js assets to js folder 
- [x] configure readthedocs from the readthedocs settings instead of yaml file
- [x] do we actually use pyproject.toml?

**Comment by ceball** [comment]
> do we actually use pyproject.toml?

@timkpaine as far as I know it's the only python way to specify "build time" dependencies ("build time" covering quite a few scenarios).

(ignoring other ecosystems e.g. conda, which has requirements/build or requirements/host in meta.yaml and what have you)

**Comment by timkpaine** [comment]
@ceball I understand the logic behind it, but im curious if we actually rely on it anywhere. all part of my considering moving to poetry

**Comment by ceball** [comment]
@timkpaine using poetry doesn't seem related to removing pyproject.toml, since poetry uses pyproject.toml, but I'm sure you already know that, so I'm still misunderstanding :) But I'm totally onboard with the aim of this issue.

First, I'll just describe some current stuff about celltests. Then I'll try to expand your question and you can correct me where I go wrong.

But before that, the short version is that I _think_ your question might be (I'm really not sure): 
  * What does nbcelltests use from setuptools/jupyter-packaging (an extension of setuptools for jupyter stuff?) that is not supported/available/possible with - or adaptable to - poetry?

## current situation

What python config files do we have and why? (I didn't create them ;)

  * `pyproject.toml`: lists build deps (i.e. allow pip to know what tools it should install "for setup.py to run"); turns on pip build isolation by default, which means better reproducibility of builds (but if you have long build times, or need to ensure binary compatibility between build/run, and so on, can be annoying...). 
  * `setup.cfg`:
    * required to specify that when a wheel's built, it should be universal (i.e. not just pure python, but python 2 and 3 compatible)
    * used for flake8 config (flake8 can only be configured in `setup.cfg`, `tox.ini`, or `.flake8`).
  * `setup.py`:
    * lists end user run time deps
    * lists developer deps
    * lists metadata like authors, version, classifiers, etc
    * defines some ?setuptools/distutils commands, for handling "jupyter nbextension and lab stuff" (more on this below)
  * `MANIFEST.in`: more control over files that end up in distributions (e.g. adds docs, jupyterlab_celltests files, etc)

Please edit and/or correct in a comment!

As an aside, we could also possibly (but probably not) count:
  * a conda.yaml file on conda-forge, which repeats the metadata and "build"+run+test dependencies
  * ...and the same again if e.g. celltests were installable via apt or whatever else

## what does it mean to move to poetry?

I'll try to expand your question - tell me where I go wrong :) Not only do I not know exactly what your question is, I have never actually used poetry, and I don't know what jupyter-packaging is/does (beyond guessing).

Current situation:
* nbcelltests is a setuptools-based project. 
* our build dependencies are setuptools, wheel, and jupyter-packaging
* the above build dependencies are required to create a wheel, create _or install_ an sdist, install from github (e.g. `pip install git+https://github...`), do an editable/dev install (`pip install -e . ...`), and so on.

What you're considering:
* switch nbcelltests to use poetry instead of setuptools+pip for development and package building

Note: this would have no impact on most _users_, as I expect most users get nbcelltests via a wheel. Wheel installation does not require executing setup.py or any of that stuff - as long as a wheel is generated, users don't care if it was via poetry or you wrote it out by hand ;) _Some_ users will get nbcelltests via sdist (or e.g. from github source), and they _will_ need to execute the build system - they are basically in the same position as developers.

Advantages:
* metadata like authors etc would move from python code in setup.py to simpler/static pyproject.toml
* dependencies would move from python code in setup.py to simpler/static pyproject.toml
* ? "one file", pyproject.toml, to configure everything (on the python side!) rather than 4
* access to poetry features, e.g. commands to add/remove deps to the project, have a lock file, dependency solver, manage a virtual env, ... ?

Questions:
* What does jupyter-packaging do/could it be used with poetry/could it be translated to poetry?
* does wheel really need setup.cfg (last time I checked, a couple of years ago: yes)
* can flake8 really not use pyproject.toml (...as I recall, pyproject.toml was not originally supposed to be a dumping ground for all tool config, that's just what's happened...apparently some people still resist it? ;) )
* does poetry bundle tests with packages? poetry projects I've seen always seem to have tests/ outside the package
* ... (I've never used poetry, so I have lots of basic questions, plus I also wonder how it interacts with other useful tools such as tox)

-----

Other misc notes:
* If we switched to poetry, we/others could still support build systems other than poetry via a tool like dephell (which can e.g. generate setup.py from pyproject.toml).
* This topic often seems like a miserable losing battle, ha ha.
