### ISSUE TITLE
Proposal for when cells/tests should execute

### ISSUE THREAD

**Issue by ceball** [jpmorganchase/nbcelltests#169]
## Summary

All cells will execute by default when you run celltests, but if you write a test for a cell, that test must either include the cell (i.e. use `%cell`) or explicitly exclude it (i.e. use `# no %cell`).

There'll be no "test skipping" any more: either a cell's test is valid (as above) and so will be run, or there will be an error during test file generation. Coverage is what will tell someone which cells have/have not executed.

Note: "test file generation" refers to generation of test script that will subsequently be executed later, but you could read it as "test collection".

## Details

Not sure I'll get these right by writing them out before implementation, but here goes...

* Cell is not a code cell but test ast not empty: error during test file generation. [1]

(the following points apply to code cells only)

* Cell is only whitespace but test ast is not empty: error during test file generation. [2]

* Cell's test is undefined or only whitespace: test runs and defaults to `%cell`. 
  * Note: this also means that by default, all cells will execute during celltests. I think that's what you would expect when you run celltests. If you don't want a cell to run, you have to explicitly do something.

* Cell's test contains `%cell`: test runs as written.

* Cell's test contains `# no %cell`: test runs as written (and the corresponding cell is not executed).

* Cell's test ast is not empty and does not contain either `%cell` or `# no %cell`: error during test file generation.

* Cell's test contains both `%cell` and `# no %cell` comment: error during test file generation.

-----

[1] Yes, the lab frontend should help more than it does about this, but still the check makes sense as you could write metadata through a different mechanism anyway.

[2] Should this be "cell ast is empty" instead? Or should it be no error at all?

**Comment by vidartf** [comment]
For context, these are the cases that should be met:
1. If a user only wants to test cell 100, but need cells 1-99 to run as well, they shouldn't have to put "%cell" in all the preceding cell tests.
2. If a user wants to mock out cell 50 above (prevent its source from running when setting the context for cell 100), that should be possible.
3. Cells with empty cellltest metadata should either (a) not generate tests or (b) generate a test that is marked as "skipped".

I'm thinking, if we want to support other kernels than just Python, then maybe the behavior of looking at AST / comments are not the cleanest. As such, I have two other alternatives.

### Alternative 1:

- Have a UI checkbox "Mock" that maps to a metadata boolean (we should namespace our metadata ASAP).

- If a cell has the "mock" set to true:
  - If `%cell` is in the test source, error that cell's test (nonsensical)
  - Otherwise, use the test source both for the test itself, and for setting the state for subsequent cells. (pt 2. above)

- If a cell has "mock" as undefined or any other value than true:
  - If the cell test is empty (strictly: undefined or whitespace only) generate no test / skip (pt. 3. a/b above). Execute the cell as normal for setting the state for subsequent cells.
  - If the test has no `%cell` in it, warn the user and/or cause that cell's test to error.
  - Otherwise generate a test as currently done.


### Alternative 2

- Have a cell tag "nbcelltest-skip-cell" (or a checkbox "skip cell")

- If the cell test is empty (strictly: undefined or whitespace only) generate no test / skip (pt. 3. a/b above). Execute the cell as normal for setting the state for subsequent cells, unless "skip cell" is defined (either checkbox and/or tag).
- If the cell test has content, run that both for the test and for setting state for subsequent state.
- If a cell's test has content but not `%cell`, give a visual indicator/warning in the UI (but do not warn when running the test).

**Comment by vidartf** [comment]
@ceball  I think my modified alternative 2 now is pretty close to your proposal?

**Comment by ceball** [comment]
Regarding the cases, I'd add: 

  0. Should be possible to take any notebook and run it with celltests, getting a meaningful result without having to modify the notebook first.

"meaningful result" could be e.g. a clear answer that nothing ran - i.e. probably shouldn't get "success" for running celltests on a notebook where nothing at all runs because you didn't put in a single test.

I _think_ "meaningful result" for me would be whether or not the notebook runs all the way through. It's like doing "restart kernel and run all cells". But you might disagree? 


I agree with cases 1 and 2. 3 we maybe don't agree on. I'll try to illustrate that by comparing Alternative 2 and the original proposal (since I believe it's the same in Alternative 1). 
  * In the original, if cell n's test is empty, there will be a `test_cell_n` method that executes cell n (and its predecessor cells if necessary; i.e. same as having just `%cell` in cell n's test). cell n will also be a prerequisite of any subsequent tests (i.e. will run for `test_cell_n+1`, if `test_cell_n` has not been run).
  * In alternative 2, if cell n's test is empty, `test_cell_n` will either show as "skipped" or no test method will be generated. You can't explicitly request to "run `test_cell_n` (and predecessors)". The only way to run cell n during celltests is to run `test_cell_>n`.

**Comment by ceball** [comment]
More ways to skip is fine/I agree with it/it's not really a difference I want to consider at this stage (I think). We should create an issue something like, "Control cell skipping/mocking other than by comments in the code" (it's in the same spirit as #141). Do you agree?

We should create an issue for namespacing the metadata. Would you be able to do that, ideally with some example/standard to follow (I'm guessing you know one...I would have to go searching :)).

**Comment by ceball** [comment]
I think Alternative 1 is almost the same as the original proposal, but with a nicer way of declaring "don't execute the cell" than via a comment. I.e. you have to say, "I'm mocking the whole cell" if you don't want to execute the cell at all. That is now covered by feature request #171.

**Comment by ceball** [comment]
Notes from conversation with @vidartf:
  1. It's important to consider future support of other kernels. While not currently a primary goal, we shouldn't go down a path that precludes supporting other kernels. So things like checking "is empty?" based on ast, looking for python comments, etc, should not mean celltests can never be used with other kernels. (Same spirit as #171, #141)
  2. The proposal here does not follow case 3. Case 3 is about the desire to ensure there is a real/deliberate test of a cell. The _current_ behavior of celltests is to generate a skipped test method if the cell is not injected, which makes it obvious the cell is not being run. However, it then is unclear to the user if that means the whole 'cell test' is being skipped, or just the cell. And the cell or its test would still need to be run for subsequent cells, so the "skipped" thing actually ends up being executed anyway (that's what #166 was going to allow, and what case 3 is about). That all gets a bit complicated to describe to users (and is the same whether test methods are skipped or instead not generated in the first place). We might revisit this after user testing and after considering how to display more useful information in jupyter lab itself.
